version: '3.7'

networks:
    frontend:

volumes:
    plex:
    nzbget:
    sonarr:
    radarr:
    hydra:
    traefik:

services:

    # https://hub.docker.com/r/plexinc/pms-docker
    plex:
        image: plexinc/pms-docker:latest
        environment:
            PLEX_UID: '${PUID}'
            PLEX_GID: '${PGID}'
            TZ: '${TZ}'
            PLEX_CLAIM: '${PLEX_CLAIM}'
            ADVERTISE_IP: '${ADVERTISE_IP}'
        networks:
            - frontend
        ports:
            - '32400:32400/tcp'
        volumes:
            - 'plex:/config'
            - '${MEDIA_DIR}:/media'
            - '${MUSIC_DIR}:/music'
            - '/tmp:/tmp'
            - '${TRANSCODE_DIR}:/transcode'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.plex.tls.certresolver: prod
            traefik.http.routers.plex.rule: Host(`${PLEX_HOST}`)
            traefik.http.services.plex_mediaserver.loadbalancer.server.port: 32400
            traefik.http.services.plex_mediaserver.loadbalancer.server.scheme: http

    # https://hub.docker.com/r/linuxserver/nzbget/
    nzbget:
        image: linuxserver/nzbget
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - frontend
        volumes:
            - 'nzbget:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${NZB_INTERMEDIATE_DIR}:/intermediate'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.nzbget.rule: Host(`${NZBGET_HOST}`)
            traefik.http.routers.nzbget.tls.certresolver: prod
            traefik.http.routers.nzbget.middlewares: hsts-header, basicauth
            traefik.http.routers.nzbget-api.rule: Host(`${NZBGET_HOST}`) && PathPrefix(`/{jsonrpc:([^\/:]*:[^\/:]*/)?jsonrpc}`,`/{xmlrpc:([^\/:]*:[^\/:]*/)?xmlrpc}`)
            traefik.http.routers.nzbget-api.middlewares: hsts-header

    # https://hub.docker.com/r/linuxserver/sonarr/
    sonarr:
        image: linuxserver/sonarr
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - frontend
        volumes:
            - 'sonarr:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${MEDIA_DIR}:/media'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.sonarr.rule: Host(`${SONARR_HOST}`)
            traefik.http.routers.sonarr.tls.certresolver: prod
            traefik.http.routers.sonarr.middlewares: hsts-header, basicauth
            traefik.http.routers.sonarr-api.rule: Host(`${SONARR_HOST}`) && PathPrefix(`/api`)
            traefik.http.routers.sonarr-api.middlewares: hsts-header
        links:
            - hydra
            - nzbget

    # https://hub.docker.com/r/linuxserver/radarr/
    radarr:
        image: linuxserver/radarr
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - frontend
        volumes:
            - 'radarr:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${MEDIA_DIR}:/media'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.radarr.rule: Host(`${RADARR_HOST}`)
            traefik.http.routers.radarr.tls.certresolver: prod
            traefik.http.routers.radarr.middlewares: hsts-header, basicauth
            traefik.http.routers.radarr-api.rule: Host(`${RADARR_HOST}`) && PathPrefix(`/api`)
            traefik.http.routers.radarr-api.middlewares: hsts-header
        links:
            - hydra
            - nzbget

    # https://hub.docker.com/r/linuxserver/nzbhydra2
    hydra:
        image: linuxserver/nzbhydra2
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - frontend
        volumes:
            - 'hydra:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.hydra.rule: Host(`${HYDRA_HOST}`)
            traefik.http.routers.hydra.tls.certresolver: prod
            traefik.http.routers.hydra.middlewares: hsts-header, basicauth
            traefik.http.routers.hydra-api.rule: Host(`${HYDRA_HOST}`) && PathPrefix(`/api`,`/getnzb`,`/gettorrent`,`/rss`,`/torznab/api`)
            traefik.http.routers.hydra-api.middlewares: hsts-header

    # https://hub.docker.com/_/traefik/
    traefik:
        image: traefik
        environment:
            TZ: '${TZ}'
        networks:
            - frontend
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - 'traefik:/etc/traefik:rw'
        command:
            - "--log.level=INFO"
            - "--api=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesResolvers.prod.acme.tlschallenge=true"
            - "--certificatesresolvers.prod.acme.storage=/etc/traefik/acme.json"
            - "--certificatesresolvers.prod.acme.email=${ACME_EMAIL}"
            - "--certificatesresolvers.prod.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
            - "--certificatesResolvers.staging.acme.tlschallenge=true"
            - "--certificatesresolvers.staging.acme.storage=/etc/traefik/acme.json"
            - "--certificatesresolvers.staging.acme.email=${ACME_EMAIL}"
            - "--certificatesresolvers.staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.traefik.rule: Host(`${TRAEFIK_HOST}`)
            traefik.http.routers.traefik.tls.certresolver: prod
            traefik.http.routers.traefik.middlewares: hsts-header, basicauth
            traefik.http.routers.traefik.service: api@internal
            traefik.http.middlewares.basicauth.basicauth.usersfile: /etc/traefik/.htpasswd
            traefik.http.middlewares.hsts-header.headers.customResponseHeaders.Strict-Transport-Security: "max-age=63072000"
